dist: trusty
language: node_js
node_js:
- stable
branches:
  only: development
notifications:

  email: karimifazlu50@gmail.com
    on_success: never        # default: change
    on_failure: always       # default: always

